# Generated by Django 4.2.11 on 2026-01-13 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategoriya nomi')),
                ('icon', models.CharField(default='📝', max_length=50, verbose_name='Ikonka')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Muammo tavsifi')),
                ('location', models.CharField(blank=True, max_length=500, null=True, verbose_name='Aniq manzil')),
                ('status', models.CharField(choices=[('new', '🆕 Yangi'), ('in_progress', '🔄 Jarayonda'), ('solved', '✅ Hal qilindi'), ('rejected', '❌ Rad etildi'), ('delayed', '⏳ Kehtirildi')], default='new', max_length=20, verbose_name='Holati')),
                ('priority', models.CharField(choices=[('low', 'Past'), ('medium', 'Oʻrta'), ('high', 'Yuqori'), ('critical', 'Judayam muhim')], default='medium', max_length=20, verbose_name='Muhimlik darajasi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Hal qilingan sana')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Administrator izohlari')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='core.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Murojaat',
                'verbose_name_plural': 'Murojaatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mahalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Mahalla nomi')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Mahalla kodi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Mahalla',
                'verbose_name_plural': 'Mahallalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('full_name', models.CharField(max_length=255, verbose_name="To'liq ism")),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqam')),
                ('role', models.CharField(choices=[('user', 'Foydalanuvchi'), ('admin', 'Administrator')], default='user', max_length=10, verbose_name='Rol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('last_active', models.DateTimeField(auto_now=True, verbose_name='Oxirgi faollik')),
            ],
            options={
                'verbose_name': 'Telegram foydalanuvchi',
                'verbose_name_plural': 'Telegram foydalanuvchilar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['telegram_id'], name='core_telegr_telegra_20a65c_idx'), models.Index(fields=['role'], name='core_telegr_role_1dbd2d_idx'), models.Index(fields=['created_at'], name='core_telegr_created_310cdf_idx')],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('new', '🆕 Yangi'), ('in_progress', '🔄 Jarayonda'), ('solved', '✅ Hal qilindi'), ('rejected', '❌ Rad etildi'), ('delayed', '⏳ Kehtirildi')], max_length=20, verbose_name='Oldingi holat')),
                ('new_status', models.CharField(choices=[('new', '🆕 Yangi'), ('in_progress', '🔄 Jarayonda'), ('solved', '✅ Hal qilindi'), ('rejected', '❌ Rad etildi'), ('delayed', '⏳ Kehtirildi')], max_length=20, verbose_name='Yangi holat')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name="O'zgartirilgan sana")),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="O'zgartirgan")),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='core.complaint', verbose_name='Murojaat')),
            ],
            options={
                'verbose_name': 'Holat tarixi',
                'verbose_name_plural': 'Holat tarixlari',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_message_id', models.BigIntegerField(verbose_name='Kanal xabar IDsi')),
                ('file_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fayl ID')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='Fayl hajmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.complaint', verbose_name='Murojaat')),
            ],
            options={
                'verbose_name': 'Murojaat rasmi',
                'verbose_name_plural': 'Murojaat rasmlari',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='complaint',
            name='mahalla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='core.mahalla', verbose_name='Mahalla'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='core.telegramuser', verbose_name='Foydalanuvchi'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_complaint', 'Yangi murojaat'), ('status_change', "Holat o'zgarishi"), ('admin_message', 'Administrator xabari'), ('reminder', 'Eslatma')], max_length=20, verbose_name='Xabar turi')),
                ('message', models.TextField(verbose_name='Xabar matni')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.complaint', verbose_name='Murojaat')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.telegramuser', verbose_name='Qabul qiluvchi')),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='core_notifi_recipie_aeffaf_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status'], name='core_compla_status_5d4f5d_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['priority'], name='core_compla_priorit_ecf673_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['created_at'], name='core_compla_created_f58568_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['mahalla', 'status'], name='core_compla_mahalla_3ce8e2_idx'),
        ),
    ]
